services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: back
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mysql-client:
    image: mysql:latest
    container_name: mysql-client
    command: tail -f /dev/null
    depends_on:
      - mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  nestjs:
    build: .
    image: nestjs:v1
    container_name: nestjs
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
      - redis
    develop:
      watch:
        - action: sync
          path: ./
          target: /${WORK_DIR}
          ignore:
            - node_modules
        - action: rebuild
          path: package.json

volumes:
  mariadb_data:
    driver: local