services:
  mariadb:
    image: mariadb:11.2.4
    container_name: mariadb
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: back
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpymyadmin
    environment:
      APACHE_SERVER_NAME: localhost
      PMA_HOST: ${PMA_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  mysql-client:
    image: mysql:8.0
    container_name: mysql-client
    command: tail -f /dev/null
    depends_on:
      - mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  back:
    image: registry.alt-tools.tech/aquildev/projet-ecole/back:test
    container_name: back
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_TOKEN: ${JWT_REFRESH_TOKEN}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
      - redis

volumes:
  mariadb_data: