services:
  mariadb:
    image: mariadb:11.2
    container_name: mariadb
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: back
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend-network

  phpmyadmin:
    image: phpmyadmin:5.2-fpm-alpine
    container_name: phpmyadmin
    environment:
      APACHE_SERVER_NAME: localhost
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - backend-network

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend-network
    volumes:
      - redis_data:/data

  mysql-client:
    image: mysql:8.0
    container_name: mysql-client
    command: tail -f /dev/null
    depends_on:
      - mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - backend-network

  back:
    image: registry.alt-tools.tech/aquildev/projet-ecole/back:test
    container_name: back
    environment:
      PORT: 3000
      DATABASE_URL: mysql://root:pass_word@mariadb:3306/back
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_TOKEN: ${JWT_REFRESH_TOKEN}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
      - redis
    networks:
      - backend-network

volumes:
  mariadb_data:
  redis_data:

networks:
  backend-network: